# Generated by Django 3.1.4 on 2020-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitstock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockKData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('close', models.DecimalField(decimal_places=10, max_digits=20)),
                ('peTTM', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pbMRQ', models.DecimalField(decimal_places=10, max_digits=20)),
                ('psTTM', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pcfNcfTTM', models.DecimalField(decimal_places=10, max_digits=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
