# Generated by Django 3.1.5 on 2020-12-29 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kitstock', '0002_stockkdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfobase',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 3, 16, 0, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='stockkdata',
            unique_together={('code', 'date')},
        ),
    ]
